# Matrices operation

### Arithmetic operation

In [1]:
mat1 <- matrix(11:20,nrow=2)

In [2]:
mat2 <- matrix(1:10,nrow=2)

In [3]:
print(mat1)

     [,1] [,2] [,3] [,4] [,5]
[1,]   11   13   15   17   19
[2,]   12   14   16   18   20


In [4]:
print(mat2)

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10


In [5]:
# operation

print(mat1 + mat2)

     [,1] [,2] [,3] [,4] [,5]
[1,]   12   16   20   24   28
[2,]   14   18   22   26   30


In [6]:
print(mat1 * mat2)

     [,1] [,2] [,3] [,4] [,5]
[1,]   11   39   75  119  171
[2,]   24   56   96  144  200


<p> The above matrix multiplication is a simple arithmetic multiplication</p>

<p> For the actual matrix multiplication use <b>%*%</b> operator </p>

In [7]:
mat3 <- matrix(2:5,nrow=2)

In [8]:
mat4 <- matrix(6:9,nrow=2)

In [9]:
print(mat3)

     [,1] [,2]
[1,]    2    4
[2,]    3    5


In [10]:
print(mat4)

     [,1] [,2]
[1,]    6    8
[2,]    7    9


In [11]:
print(mat3 %*% mat4)

     [,1] [,2]
[1,]   40   52
[2,]   53   69


<hr>
<p> Matrix and scalar operation </p>

In [12]:
print(mat1 * 4)

     [,1] [,2] [,3] [,4] [,5]
[1,]   44   52   60   68   76
[2,]   48   56   64   72   80


In [13]:
print(mat1 ^ 2)

     [,1] [,2] [,3] [,4] [,5]
[1,]  121  169  225  289  361
[2,]  144  196  256  324  400


In [14]:
print(1 / mat1)

           [,1]       [,2]       [,3]       [,4]       [,5]
[1,] 0.09090909 0.07692308 0.06666667 0.05882353 0.05263158
[2,] 0.08333333 0.07142857 0.06250000 0.05555556 0.05000000


### Comparison operation

In [15]:
print(mat1 > mat2)

     [,1] [,2] [,3] [,4] [,5]
[1,] TRUE TRUE TRUE TRUE TRUE
[2,] TRUE TRUE TRUE TRUE TRUE


In [16]:
# With Scalar 
print(mat1 < 4)

      [,1]  [,2]  [,3]  [,4]  [,5]
[1,] FALSE FALSE FALSE FALSE FALSE
[2,] FALSE FALSE FALSE FALSE FALSE


### Matrices functions

In [17]:
mat <- matrix(15:20,nrow=2)

In [18]:
print(mat)

     [,1] [,2] [,3]
[1,]   15   17   19
[2,]   16   18   20


In [19]:
rownames(mat) <- c('Jack','John')

In [20]:
colnames(mat) <- c('Math','Science','English')

In [21]:
print(mat)

     Math Science English
Jack   15      17      19
John   16      18      20


<hr>
<b> rowSums() </b>

In [22]:
rowSums(mat)

Jack John 
  51   54

<b>colSums()</b>

In [23]:
colSums(mat)

Math Science English 
     31      35      39

<b>rowMeans()</b>

In [24]:
rowMeans(mat)

Jack John 
  17   18

<b>colMeans()</b>

In [25]:
colMeans(mat)

Math Science English 
   15.5    17.5    19.5

<b>rbind()</b>

<p><b>rbind()</b> function is used to bind a new row</p> 

In [26]:
Jill <- c(21,22,23)

In [27]:
mat <- rbind(mat,Jill)

In [28]:
print(mat)

     Math Science English
Jack   15      17      19
John   16      18      20
Jill   21      22      23


<b>cbind()</b>

<p><b>cbind()</b> function is used to bind a new column</p> 

In [29]:
avg <- rowMeans(mat)

In [30]:
mat <- cbind(mat,avg)

In [31]:
print(mat)

     Math Science English avg
Jack   15      17      19  17
John   16      18      20  18
Jill   21      22      23  22


### Indexing and Slicing

In [32]:
mat <- matrix(1:50,byrow=TRUE,ncol=5)

In [33]:
print(mat)

      [,1] [,2] [,3] [,4] [,5]
 [1,]    1    2    3    4    5
 [2,]    6    7    8    9   10
 [3,]   11   12   13   14   15
 [4,]   16   17   18   19   20
 [5,]   21   22   23   24   25
 [6,]   26   27   28   29   30
 [7,]   31   32   33   34   35
 [8,]   36   37   38   39   40
 [9,]   41   42   43   44   45
[10,]   46   47   48   49   50


In [34]:
# Indexing
# mat[row,col]

mat[2,4]

[1] 9

In [35]:
mat[1,]

[1] 1 2 3 4 5

In [44]:
mat[,4]

[1]  4  9 14 19 24 29 34 39 44 49

In [45]:
mat[c(1,4),c(2,3)]

[,1] [,2]
[1,]  2    3  
[2,] 17   18

In [37]:
#Slicing

print(mat[1:2,2:4])

     [,1] [,2] [,3]
[1,]    2    3    4
[2,]    7    8    9


In [38]:
print(mat[1:2,2])

[1] 2 7


In [39]:
print(mat[2,2:4])

[1] 7 8 9


In [42]:
# Conditional selection

mat[mat%%2==0]

[1]  6 16 26 36 46  2 12 22 32 42  8 18 28 38 48  4 14 24 34 44 10 20 30 40 50