# Matrices

<p>1) Matrices are two dimensional array that can store homogeneous (same data type) data.</p>
<p> 2) Matrices are created using matrix function <b>matrix()</b></p>

### Creating matrix from a vector

In [18]:
v <- 1:10

In [19]:
print(v)

 [1]  1  2  3  4  5  6  7  8  9 10


In [20]:
m1 <- matrix(v)

In [10]:
print(m1)

      [,1]
 [1,]    1
 [2,]    2
 [3,]    3
 [4,]    4
 [5,]    5
 [6,]    6
 [7,]    7
 [8,]    8
 [9,]    9
[10,]   10


<hr>
<p>Mention number of rows and columns using <b>nrow</b> and <b>ncol</b> arguments</p>

In [21]:
m2 <- matrix(v,nrow=2)

In [22]:
print(m2)

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10


In [26]:
m3 <- matrix(v,ncol=5)

In [27]:
print(m3)

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10


<hr>
<p>1) In a matrix,data is filled column wise by default. </p>
<p>2) This is because of <b>byrow</b> argument which is <b>FALSE</b> by default </p>
<p>matrix(v,byrow=False)</p>

In [33]:
m4 <- matrix(v,byrow=FALSE,nrow=2)

In [34]:
print(m4)

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10


In [35]:
#Filling data row wise

m5 <- matrix(v,byrow=TRUE,nrow=2)

In [36]:
print(m5)

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    2    3    4    5
[2,]    6    7    8    9   10


### Naming rows and columns of matrix

<p>Let's create two vectors that consist of scores of two student in various subjects</p>

In [37]:
v1 <- c(56,78,81)
v2 <- c(79,67,86)

In [38]:
# Combine both vectors
scores <- c(v1,v2)

In [40]:
print(scores)

[1] 56 78 81 79 67 86


In [43]:
# Convert the vector into matrix with nrow=2, since we have 2 students
# Fill the matrix with rows, with byrow=TRUE

mat <- matrix(scores, nrow=2, byrow=TRUE)

In [45]:
print(mat)

     [,1] [,2] [,3]
[1,]   56   78   81
[2,]   79   67   86


In [47]:
# Let's create two vectors for row and col names

subjects <- c('Math','Science','English')

students <- c('Jack','John')

<p> name rows and columns using <b>rownames()</b> and <b>colnames()</b> function </p>

In [48]:
rownames(mat) <- students
colnames(mat) <- subjects

In [49]:
print(mat)

     Math Science English
Jack   56      78      81
John   79      67      86
